- hosts: localhost
  become: yes
  become_method: sudo
  roles:
    - {role: nodejs, tags: ['nodejs'] }
    - {role: docker, tags: ['docker'] }
    - {role: oracle-jdk, tags: ['jdk'] }
    - {role: intellij, tags: ['intellij'] }
